#extends: ["spectral:oas"]

functions: [codeDescriptions]
rules:
  unify-4xx-descriptions:
    description: "Ensure 4XX responses have the correct description according to the standard."
    given: "$.components.responses"
    severity: error
    then:
        function: codeDescriptions
        functionOptions:
          validCodes:
            - 400
            - 401
    