#extends: ["spectral:oas"]

functions: [codeDescriptions]
rules:
  unify-4xx-descriptions:
    description: "Ensure 4XX responses have the correct description according to the standard."
    given: "$.components.responses"
    severity: error
    then:
        function: codeDescriptions
        functionOptions:
          validCodes: #Añadir aqui todos los codigos de estado que desees comprobar.
            - 400
            - 401
            - 403
            - 404
            - 406 
            - 415
            - 422
            - 429
            - 200 

    